//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MainApp.rc
//
#define IDCANCLE                        2
#define IDD_ABOUTBOX                    100
#define IDD_OPENURL                     101
#define IDD_LEFTBAR                     102
#define ID_VIEW_LEFTBAR                 103
#define IDD_BOTTOMBAR                   104
#define ID_VIEW_BOTTOMBAR               105
#define IDB_SPLASH                      106
#define IDR_MAINFRAME                   128
#define IDR_RIGHTVIEWMENU               129
#define IDB_BACKGROUND                  130
#define IDR_HIDDEN                      130
#define IDB_ORANGE                      131
#define IDD_INSERTDIALOG                131
#define IDB_BLUE                        133
#define IDD_BOX                         133
#define IDB_RED                         134
#define IDD_MATERIALS                   134
#define IDB_GREEN                       135
#define IDD_TEXTURE                     135
#define IDD_CONE                        136
#define IDB_ABOUTBMP                    136
#define IDD_SPHERE                      137
#define IDD_CYLINDER                    138
#define IDB_LOGO                        138
#define IDD_ELEVATIONGRID               139
#define IDC_SENSOR                      139
#define IDD_PREFERENCES                 140
#define IDD_VIEWPOINTS                  141
#define IDD_SPLITTESTS                  154
#define IDD_BOOLTESTS                   156
#define IDC_URL                         1000
#define IDC_BROWSE                      1001
#define IDC_ADD                         1002
#define IDC_GEOMETRYTYPE                1002
#define IDC_PRESERVE                    1003
#define IDC_INSERTGEOM                  1003
#define IDC_LIGHTTYPE                   1004
#define IDC_PROPERTIES                  1004
#define IDC_INSERTLIGHT                 1005
#define IDC_EDIT1                       1005
#define IDC_AMBIENT                     1005
#define IDC_SPLITSHIT                   1005
#define IDC_EDIT2                       1006
#define IDC_TRANSPARENT                 1006
#define IDC_EDIT3                       1007
#define IDC_SHININESS                   1007
#define IDC_BOXX                        1008
#define IDC_ZSPACE                      1008
#define IDC_BOXY                        1009
#define IDC_BOXZ                        1010
#define IDC_CONEHEIGHT                  1011
#define IDC_CONERAD                     1012
#define IDC_CONESHOWSIDES               1013
#define IDC_CONESHOWBOTTOM              1014
#define IDC_SPHERERAD                   1014
#define IDC_CONESHOWTOP                 1015
#define IDC_HEIGHTFUNC                  1015
#define IDC_COLORS                      1016
#define IDC_XDIM                        1017
#define IDC_ZDIM                        1018
#define IDC_XSPACE                      1019
#define IDC_TESTNUM                     1020
#define IDC_NONE                        1023
#define IDC_CHECKED                     1024
#define IDC_NATIVE                      1024
#define IDC_CROSSES                     1025
#define IDC_CIRCLE                      1026
#define IDC_RAMP                        1027
#define IDC_STARTCOLOR                  1028
#define IDC_STOPCOLOR                   1029
#define IDC_MANDRILL                    1030
#define IDC_MODULATES                   1031
#define IDC_EMISSIVE                    1032
#define IDC_DIFFUSE                     1033
#define IDC_SPEC                        1034
#define IDC_RESET                       1037
#define IDC_AUTOROTATE                  1038
#define IDC_SAVEFILENAMEONLOAD          1039
#define IDC_HEADSUPDISPLAY              1040
#define IDC_ITERATIONS                  1040
#define IDC_EXPORTALLFIELDS             1041
#define IDC_BALL                        1041
#define IDC_MERGE                       1042
#define IDC_COMBO1                      1043
#define IDC_BALL2                       1043
#define IDC_VIEWPOINTLIST               1044
#define IDC_NAVMODE                     1044
#define IDC_AUTO                        1048
#define IDC_OPERATION                   1052
#define IDC_GROUP                       1053
#define ID_VIEW_RIGHTVIEW               32771
#define ID_HELP_CONTENTS                32773
#define ID_HELP_WEB                     32774
#define ID_NAVIGATION_WALK              32775
#define ID_NAVIGATION_SLIDE             32776
#define ID_NAVIGATION_ROTATEZ           32777
#define ID_NAVIGATION_ROTATEX           32778
#define ID_NAVIGATION_EXAMINE           32779
#define ID_VIEW_SOURCE                  32780
#define ID_VIEW_BACKGROUND              32783
#define ID_FILE_KILLALL                 32784
#define ID_INSERT_INSERT                32785
#define ID_VIEW_DRAWMODE_POLYGONS       32786
#define ID_VIEW_DRAWMODE_LINES          32787
#define ID_VIEW_DRAWMODE_POINTS         32788
#define ID_VIEW_LIGHTS                  32789
#define ID_FILE_RELOAD                  32790
#define ID_FILE_IMPORT                  32791
#define ID_VIEW_BOUNDINGBOXES           32792
#define ID_VIEW_CENTER                  32793
#define ID_FILE_EXPORT                  32794
#define ID_VIEW_HEADSUPDISPLAY          32795
#define ID_NAVIGATION_ROTATEY           32797
#define ID_NAVIGATION_AUTOANIMATE       32798
#define ID_NAVIGATION_STRAIGHTEN        32799
#define ID_VIEW_INBROWSER               32800
#define ID_HIDDEN_QUICKOPEN             32801
#define ID_FILE_PREFERENCES             32803
#define ID_VIEWPOINTS_NEXT              32806
#define ID_VIEWPOINTS_PREV              32807
#define ID_VIEWPOINTS_LIST              32808
#define ID_0_TESTING                    32811
#define ID_SOLIDMODEL_PROPERTIES        32812
#define ID_SOLIDMODEL_ALGORITHMS_TEST1  32816
#define ID_SOLIDMODEL_ALGORITHMS_TEST2  32817
#define ID_SOLIDMODEL_SPLITPLANE_TEST1  32818
#define ID_SOLIDMODEL_SPLITPLANE_TEST2  32819
#define ID_SOLIDMODEL_BOOLEAN_TEST1     32820
#define ID_SOLIDMODEL_BOOLEAN_TEST2     32821
#define ID_SOLIDMODEL_OBJECTS_BALL      32823
#define ID_SOLIDMODEL_OBJECTS_CAR       32825
#define ID_SOLIDMODEL_OBJECTS_PEDRO     32828
#define ID_SOLIDMODEL_OBJECTS_PLANT     32829
#define ID_SOLIDMODEL_OBJECTS_TWIST     32832
#define ID_HELP_SDKDOCUMENTATION        32835
#define ID_INSERT_SOLIDOBJECTS_TWIST2   32836
#define ID_INSERT_SOLIDALGORITHMS_TRANSLATIONALSWEEP 32837
#define ID_INSERT_SOLIDALGORITHMS_ROTATIONALSWEEP 32838
#define ID_INSERT_SOLIDBOOLEAN          32840
#define ID_INSERT_BOOLTESTS2_FACTORYPART 32846
#define ID_INSERT_BOOLTESTS2_TABLE      32847
#define ID_HELP_CONTENTS_HELP           32848
#define ID_0_AUTOTEST                   32849

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
