//-------------------------------------------------------------------------
//  Copyright (c) 1997-1998 Great Hill Corporation
//  All Rights Reserved.
//
//  For conditions of distribution and use of this software,
//  please see copyright notice in utility.h
//-------------------------------------------------------------------------
#include "types.h"

#include "sfcolor.h"

SFColor colorMap[] = {
	vrBlack,
	vrWhite,
	vrRed,
	vrGreen,
	vrBlue,
	vrYellow,
	vrCyan,
	vrMagenta,
	vrAquamarine,
	vrBlueViolet,
	vrBrown,
	vrCadetBlue,
	vrCoral,
	vrCornflowerBlue,
	vrDarkGreen,
	vrDarkOliveGreen,
	vrDarkOrchid,
	vrDarkSlateBlue,
	vrDarkSlateGray,
	vrDarkSlateGrey,
	vrDarkTurquoise,
	vrDimGray,
	vrDimGrey,
	vrFirebrick,
	vrForestGreen,
	vrGold,
	vrGoldenrod,
	vrGray,
	vrGreenYellow,
	vrGrey,
	vrIndianRed,
	vrKhaki,
	vrLightBlue,
	vrLightGray,
	vrLightGrey,
	vrLightSteelBlue,
	vrLimeGreen,
	vrMaroon,
	vrMediumAquamarine,
	vrMediumBlue,
	vrMediumForestGreen,
	vrMediumGoldenrod,
	vrMediumOrchid,
	vrMediumSeaGreen,
	vrMediumSlateBlue,
	vrMediumSpringGreen,
	vrMediumTurquoise,
	vrMediumVioletRed,
	vrMidnightBlue,
	vrNavy,
	vrNavyBlue,
	vrOrange,
	vrOrangeRed,
	vrOrchid,
	vrPaleGreen,
	vrPink,
	vrPlum,
	vrSalmon,
	vrSeaGreen,
	vrSienna,
	vrSkyBlue,
	vrSlateBlue,
	vrSpringGreen,
	vrSteelBlue,
	vrTan,
	vrThistle,
	vrTurquoise,
	vrViolet,
	vrVioletRed,
	vrWheat,
	vrYellowGreen
};
SFInt32 MAX_COLORS=sizeof(colorMap)/sizeof(SFColor);

